# Generated by Django 4.2.1 on 2023-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0004_alter_menuitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(db_index=True, default="2023-06-14T17:54:45.083140"),
        ),
    ]
