# Generated by Django 4.2.1 on 2023-06-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0005_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="date", field=models.DateField(db_index=True),
        ),
    ]
